HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Mon, 28 Dec 2015 14:18:07 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Status: 500 Internal Server Error
Cache-Control: no-cache
X-Request-Id: ed8acc9f-9272-4286-b6fb-0ee79b10e180
X-Runtime: 0.008398

{"message":"Internal Server Error"}
